import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConnection } from "./db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnection();
  return (
    <html lang="en">
      <head>
        <link
          data-default-icon="https://static.cdninstagram.com/rsrc.php/v3/yI/r/VsNE-OHk_8a.png"
          rel="icon"
          sizes="192x192"
          href="https://static.cdninstagram.com/rsrc.php/v3/yI/r/VsNE-OHk_8a.png"
        />
        <link
          data-default-icon="https://static.cdninstagram.com/rsrc.php/y4/r/QaBlI0OZiks.ico"
          rel="shortcut icon"
          type="image/x-icon"
          href="https://static.cdninstagram.com/rsrc.php/y4/r/QaBlI0OZiks.ico"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
